import {GetStaticProps, NextPage} from "next";
import Head from "next/head";

const EnvSample: NextPage = (props) => {

    console.log('process.env.TEST', process.env.TEST)
    console.log('process.env.NEXT_PUBLIC_TEST', process.env.NEXT_PUBLIC_TEST)

    const aaa = process.env.TEST === undefined ? 'undefined' : process.env.TEST;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div>
                    {aaa === undefined ? <p suppressHydrationWarning></p> : <p suppressHydrationWarning>{aaa}</p>}
                    <p>{process.env.NEXT_PUBLIC_TEST}</p>
                </div>
            </main>
        </>
    )
}

export const getStaticProps: GetStaticProps = async (context) => {

    console.log('process.env.TEST', process.env.TEST)
    console.log('process.env.NEXT_PUBLIC_TEST', process.env.NEXT_PUBLIC_TEST)

    return {
        props: {},
    }
}

export default EnvSample